const vaccinationData = {
    "graphData":[
        {
            "case_date":"2021-02-28",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-01",
            "total_vaccinations":756
        },
        {
            "case_date":"2021-03-02",
            "total_vaccinations":2793
        },
        {
            "case_date":"2021-03-03",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-04",
            "total_vaccinations":10000
        },
        {
            "case_date":"2021-03-05",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-06",
            "total_vaccinations":25138
        },
        {
            "case_date":"2021-03-07",
            "total_vaccinations":29266
        },
        {
            "case_date":"2021-03-08",
            "total_vaccinations":44000
        },
        {
            "case_date":"2021-03-09",
            "total_vaccinations":89077
        },
        {
            "case_date":"2021-03-10",
            "total_vaccinations":114500
        },
        {
            "case_date":"2021-03-11",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-12",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-13",
            "total_vaccinations":193492
        },
        {
            "case_date":"2021-03-14",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-15",
            "total_vaccinations":215997
        },
        {
            "case_date":"2021-03-16",
            "total_vaccinations":216794
        },
        {
            "case_date":"2021-03-17",
            "total_vaccinations":269583
        },
        {
            "case_date":"2021-03-18",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-19",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-20",
            "total_vaccinations":336656
        },
        {
            "case_date":"2021-03-21",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-22",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-23",
            "total_vaccinations":508332
        },
        {
            "case_date":"2021-03-24",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-25",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-26",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-27",
            "total_vaccinations":656331
        },
        {
            "case_date":"2021-03-28",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-29",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-03-30",
            "total_vaccinations":738913
        },
        {
            "case_date":"2021-03-31",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-01",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-02",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-03",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-04",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-05",
            "total_vaccinations":855457
        },
        {
            "case_date":"2021-04-06",
            "total_vaccinations":922898
        },
        {
            "case_date":"2021-04-07",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-08",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-09",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-10",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-11",
            "total_vaccinations":1139644
        },
        {
            "case_date":"2021-04-12",
            "total_vaccinations":1202297
        },
        {
            "case_date":"2021-04-13",
            "total_vaccinations":1255716
        },
        {
            "case_date":"2021-04-14",
            "total_vaccinations":1312356
        },
        {
            "case_date":"2021-04-15",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-16",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-17",
            "total_vaccinations":1456793
        },
        {
            "case_date":"2021-04-18",
            "total_vaccinations":1477757
        },
        {
            "case_date":"2021-04-19",
            "total_vaccinations":1507547
        },
        {
            "case_date":"2021-04-20",
            "total_vaccinations":1562563
        },
        {
            "case_date":"2021-04-21",
            "total_vaccinations":1612420
        },
        {
            "case_date":"2021-04-22",
            "total_vaccinations":1666687
        },
        {
            "case_date":"2021-04-23",
            "total_vaccinations":1732359
        },
        {
            "case_date":"2021-04-24",
            "total_vaccinations":1753465
        },
        {
            "case_date":"2021-04-25",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-04-26",
            "total_vaccinations":1767940
        },
        {
            "case_date":"2021-04-27",
            "total_vaccinations":1809801
        },
        {
            "case_date":"2021-04-28",
            "total_vaccinations":1849566
        },
        {
            "case_date":"2021-04-29",
            "total_vaccinations":1880975
        },
        {
            "case_date":"2021-04-30",
            "total_vaccinations":1919851
        },
        {
            "case_date":"2021-05-01",
            "total_vaccinations":1941196
        },
        {
            "case_date":"2021-05-02",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-05-03",
            "total_vaccinations":1999214
        },
        {
            "case_date":"2021-05-04",
            "total_vaccinations":2065235
        },
        {
            "case_date":"2021-05-05",
            "total_vaccinations":2129185
        },
        {
            "case_date":"2021-05-06",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-05-07",
            "total_vaccinations":2314377
        },
        {
            "case_date":"2021-05-08",
            "total_vaccinations":2395494
        },
        {
            "case_date":"2021-05-09",
            "total_vaccinations":2408781
        },
        {
            "case_date":"2021-05-10",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-05-11",
            "total_vaccinations":2542066
        },
        {
            "case_date":"2021-05-12",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-05-13",
            "total_vaccinations":2714677
        },
        {
            "case_date":"2021-05-14",
            "total_vaccinations":2790287
        },
        {
            "case_date":"2021-05-15",
            "total_vaccinations":2921196
        },
        {
            "case_date":"2021-05-16",
            "total_vaccinations":3001875
        },
        {
            "case_date":"2021-05-17",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-05-18",
            "total_vaccinations":3299470
        },
        {
            "case_date":"2021-05-19",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-05-20",
            "total_vaccinations":3718308
        },
        {
            "case_date":"2021-05-21",
            "total_vaccinations":3956292
        },
        {
            "case_date":"2021-05-22",
            "total_vaccinations":4097425
        },
        {
            "case_date":"2021-05-23",
            "total_vaccinations":4169905
        },
        {
            "case_date":"2021-05-24",
            "total_vaccinations":4305575
        },
        {
            "case_date":"2021-05-25",
            "total_vaccinations":4495375
        },
        {
            "case_date":"2021-05-26",
            "total_vaccinations":4666358
        },
        {
            "case_date":"2021-05-27",
            "total_vaccinations":4862358
        },
        {
            "case_date":"2021-05-28",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-05-29",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-05-30",
            "total_vaccinations":5180721
        },
        {
            "case_date":"2021-05-31",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-06-01",
            "total_vaccinations":5382172
        },
        {
            "case_date":"2021-06-02",
            "total_vaccinations":5517523
        },
        {
            "case_date":"2021-06-03",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-06-04",
            "total_vaccinations":5828735
        },
        {
            "case_date":"2021-06-05",
            "total_vaccinations":5907255
        },
        {
            "case_date":"2021-06-06",
            "total_vaccinations":5965651
        },
        {
            "case_date":"2021-06-07",
            "total_vaccinations":6096208
        },
        {
            "case_date":"2021-06-08",
            "total_vaccinations":6314548
        },
        {
            "case_date":"2021-06-09",
            "total_vaccinations":6470776
        },
        {
            "case_date":"2021-06-10",
            "total_vaccinations":6614417
        },
        {
            "case_date":"2021-06-11",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-06-12",
            "total_vaccinations":6870054
        },
        {
            "case_date":"2021-06-13",
            "total_vaccinations":6948549
        },
        {
            "case_date":"2021-06-14",
            "total_vaccinations":7045380
        },
        {
            "case_date":"2021-06-15",
            "total_vaccinations":7368309
        },
        {
            "case_date":"2021-06-16",
            "total_vaccinations":7563241
        },
        {
            "case_date":"2021-06-17",
            "total_vaccinations":7848392
        },
        {
            "case_date":"2021-06-18",
            "total_vaccinations":8050711
        },
        {
            "case_date":"2021-06-19",
            "total_vaccinations":8222759
        },
        {
            "case_date":"2021-06-20",
            "total_vaccinations":8407342
        },
        {
            "case_date":"2021-06-21",
            "total_vaccinations":8591406
        },
        {
            "case_date":"2021-06-22",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-06-23",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-06-24",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-06-25",
            "total_vaccinations":9542612
        },
        {
            "case_date":"2021-06-26",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-06-27",
            "total_vaccinations":10065414
        },
        {
            "case_date":"2021-06-28",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-06-29",
            "total_vaccinations":10236354
        },
        {
            "case_date":"2021-06-30",
            "total_vaccinations":10443407
        },
        {
            "case_date":"2021-07-01",
            "total_vaccinations":10703704
        },
        {
            "case_date":"2021-07-02",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-03",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-04",
            "total_vaccinations":11708029
        },
        {
            "case_date":"2021-07-05",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-06",
            "total_vaccinations":11967805
        },
        {
            "case_date":"2021-07-07",
            "total_vaccinations":12179437
        },
        {
            "case_date":"2021-07-08",
            "total_vaccinations":12489777
        },
        {
            "case_date":"2021-07-09",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-10",
            "total_vaccinations":12942364
        },
        {
            "case_date":"2021-07-11",
            "total_vaccinations":13122277
        },
        {
            "case_date":"2021-07-12",
            "total_vaccinations":13196282
        },
        {
            "case_date":"2021-07-13",
            "total_vaccinations":13442299
        },
        {
            "case_date":"2021-07-14",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-15",
            "total_vaccinations":14074514
        },
        {
            "case_date":"2021-07-16",
            "total_vaccinations":14465786
        },
        {
            "case_date":"2021-07-17",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-18",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-19",
            "total_vaccinations":15096261
        },
        {
            "case_date":"2021-07-20",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-21",
            "total_vaccinations":15616562
        },
        {
            "case_date":"2021-07-22",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-23",
            "total_vaccinations":16426267
        },
        {
            "case_date":"2021-07-24",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-25",
            "total_vaccinations":17066135
        },
        {
            "case_date":"2021-07-26",
            "total_vaccinations":17202421
        },
        {
            "case_date":"2021-07-27",
            "total_vaccinations":17515376
        },
        {
            "case_date":"2021-07-28",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-29",
            "total_vaccinations":19359927
        },
        {
            "case_date":"2021-07-30",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-07-31",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-01",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-02",
            "total_vaccinations":20863544
        },
        {
            "case_date":"2021-08-03",
            "total_vaccinations":22488705
        },
        {
            "case_date":"2021-08-04",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-05",
            "total_vaccinations":23199187
        },
        {
            "case_date":"2021-08-06",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-07",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-08",
            "total_vaccinations":24990042
        },
        {
            "case_date":"2021-08-09",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-10",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-11",
            "total_vaccinations":26127502
        },
        {
            "case_date":"2021-08-12",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-13",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-14",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-15",
            "total_vaccinations":27806881
        },
        {
            "case_date":"2021-08-16",
            "total_vaccinations":28308493
        },
        {
            "case_date":"2021-08-17",
            "total_vaccinations":0
        },
        {
            "case_date":"2021-08-18",
            "total_vaccinations":29127240
        }
    ],
    "tableData":[
        {
            "case_date":"2021-02-28",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":0,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":0
        },
        {
            "case_date":"2021-03-01",
            "total_vaccinations":756,
            "people_vaccinated":756,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":756,
            "daily_vaccinations":756,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":7
        },
        {
            "case_date":"2021-03-02",
            "total_vaccinations":2793,
            "people_vaccinated":2793,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":2037,
            "daily_vaccinations":1396,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":13
        },
        {
            "case_date":"2021-03-03",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":2132,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":19
        },
        {
            "case_date":"2021-03-04",
            "total_vaccinations":10000,
            "people_vaccinated":10000,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":2500,
            "total_vaccinated_per_hundred":0.01,
            "people_vaccinated_per_hundred":0.01,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":23
        },
        {
            "case_date":"2021-03-05",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":3514,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":32
        },
        {
            "case_date":"2021-03-06",
            "total_vaccinations":25138,
            "people_vaccinated":25138,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":4190,
            "total_vaccinated_per_hundred":0.02,
            "people_vaccinated_per_hundred":0.02,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":38
        },
        {
            "case_date":"2021-03-07",
            "total_vaccinations":29266,
            "people_vaccinated":29266,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":4128,
            "daily_vaccinations":4181,
            "total_vaccinated_per_hundred":0.03,
            "people_vaccinated_per_hundred":0.03,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":38
        },
        {
            "case_date":"2021-03-08",
            "total_vaccinations":44000,
            "people_vaccinated":44000,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":14734,
            "daily_vaccinations":6178,
            "total_vaccinated_per_hundred":0.04,
            "people_vaccinated_per_hundred":0.04,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":56
        },
        {
            "case_date":"2021-03-09",
            "total_vaccinations":89077,
            "people_vaccinated":89077,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":45077,
            "daily_vaccinations":12326,
            "total_vaccinated_per_hundred":0.08,
            "people_vaccinated_per_hundred":0.08,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":112
        },
        {
            "case_date":"2021-03-10",
            "total_vaccinations":114500,
            "people_vaccinated":114500,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":25423,
            "daily_vaccinations":15443,
            "total_vaccinated_per_hundred":0.1,
            "people_vaccinated_per_hundred":0.1,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":141
        },
        {
            "case_date":"2021-03-11",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":18690,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":171
        },
        {
            "case_date":"2021-03-12",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":21370,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":195
        },
        {
            "case_date":"2021-03-13",
            "total_vaccinations":193492,
            "people_vaccinated":193492,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":24051,
            "total_vaccinated_per_hundred":0.18,
            "people_vaccinated_per_hundred":0.18,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":219
        },
        {
            "case_date":"2021-03-14",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":25068,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":229
        },
        {
            "case_date":"2021-03-15",
            "total_vaccinations":215997,
            "people_vaccinated":215997,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":24571,
            "total_vaccinated_per_hundred":0.2,
            "people_vaccinated_per_hundred":0.2,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":224
        },
        {
            "case_date":"2021-03-16",
            "total_vaccinations":216794,
            "people_vaccinated":216794,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":797,
            "daily_vaccinations":18245,
            "total_vaccinated_per_hundred":0.2,
            "people_vaccinated_per_hundred":0.2,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":166
        },
        {
            "case_date":"2021-03-17",
            "total_vaccinations":269583,
            "people_vaccinated":269583,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":52789,
            "daily_vaccinations":22155,
            "total_vaccinated_per_hundred":0.25,
            "people_vaccinated_per_hundred":0.25,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":202
        },
        {
            "case_date":"2021-03-18",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":21587,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":197
        },
        {
            "case_date":"2021-03-19",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":21020,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":192
        },
        {
            "case_date":"2021-03-20",
            "total_vaccinations":336656,
            "people_vaccinated":336656,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":20452,
            "total_vaccinated_per_hundred":0.31,
            "people_vaccinated_per_hundred":0.31,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":187
        },
        {
            "case_date":"2021-03-21",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":27020,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":247
        },
        {
            "case_date":"2021-03-22",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":33587,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":307
        },
        {
            "case_date":"2021-03-23",
            "total_vaccinations":508332,
            "people_vaccinated":508332,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":41648,
            "total_vaccinated_per_hundred":0.46,
            "people_vaccinated_per_hundred":0.46,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":380
        },
        {
            "case_date":"2021-03-24",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":39393,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":359
        },
        {
            "case_date":"2021-03-25",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":41484,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":379
        },
        {
            "case_date":"2021-03-26",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":43576,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":398
        },
        {
            "case_date":"2021-03-27",
            "total_vaccinations":656331,
            "people_vaccinated":656331,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":45668,
            "total_vaccinated_per_hundred":0.6,
            "people_vaccinated_per_hundred":0.6,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":417
        },
        {
            "case_date":"2021-03-28",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":41425,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":378
        },
        {
            "case_date":"2021-03-29",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":37183,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":339
        },
        {
            "case_date":"2021-03-30",
            "total_vaccinations":738913,
            "people_vaccinated":737569,
            "people_fully_vaccinated":1344,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":32940,
            "total_vaccinated_per_hundred":0.67,
            "people_vaccinated_per_hundred":0.67,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":301
        },
        {
            "case_date":"2021-03-31",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":30429,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":278
        },
        {
            "case_date":"2021-04-01",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":27918,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":255
        },
        {
            "case_date":"2021-04-02",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":25408,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":232
        },
        {
            "case_date":"2021-04-03",
            "total_vaccinations":0,
            "people_vaccinated":795320,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":22897,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0.73,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":209
        },
        {
            "case_date":"2021-04-04",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":21739,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":198
        },
        {
            "case_date":"2021-04-05",
            "total_vaccinations":855457,
            "people_vaccinated":826607,
            "people_fully_vaccinated":28850,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":20582,
            "total_vaccinated_per_hundred":0.78,
            "people_vaccinated_per_hundred":0.75,
            "people_fully_vaccinated_per_hundred":0.03,
            "daily_vaccinations_per_million":188
        },
        {
            "case_date":"2021-04-06",
            "total_vaccinations":922898,
            "people_vaccinated":872213,
            "people_fully_vaccinated":50685,
            "daily_vaccinations_raw":67441,
            "daily_vaccinations":26284,
            "total_vaccinated_per_hundred":0.84,
            "people_vaccinated_per_hundred":0.8,
            "people_fully_vaccinated_per_hundred":0.05,
            "daily_vaccinations_per_million":240
        },
        {
            "case_date":"2021-04-07",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":29701,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":271
        },
        {
            "case_date":"2021-04-08",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":33119,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":302
        },
        {
            "case_date":"2021-04-09",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":36537,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":333
        },
        {
            "case_date":"2021-04-10",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":39955,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":365
        },
        {
            "case_date":"2021-04-11",
            "total_vaccinations":1139644,
            "people_vaccinated":1007356,
            "people_fully_vaccinated":132288,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":43373,
            "total_vaccinated_per_hundred":1.04,
            "people_vaccinated_per_hundred":0.92,
            "people_fully_vaccinated_per_hundred":0.12,
            "daily_vaccinations_per_million":396
        },
        {
            "case_date":"2021-04-12",
            "total_vaccinations":1202297,
            "people_vaccinated":1053256,
            "people_fully_vaccinated":149041,
            "daily_vaccinations_raw":62653,
            "daily_vaccinations":49549,
            "total_vaccinated_per_hundred":1.1,
            "people_vaccinated_per_hundred":0.96,
            "people_fully_vaccinated_per_hundred":0.14,
            "daily_vaccinations_per_million":452
        },
        {
            "case_date":"2021-04-13",
            "total_vaccinations":1255716,
            "people_vaccinated":1093651,
            "people_fully_vaccinated":162065,
            "daily_vaccinations_raw":53419,
            "daily_vaccinations":47545,
            "total_vaccinated_per_hundred":1.15,
            "people_vaccinated_per_hundred":1,
            "people_fully_vaccinated_per_hundred":0.15,
            "daily_vaccinations_per_million":434
        },
        {
            "case_date":"2021-04-14",
            "total_vaccinations":1312356,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":56640,
            "daily_vaccinations":49444,
            "total_vaccinated_per_hundred":1.2,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":451
        },
        {
            "case_date":"2021-04-15",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":50129,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":457
        },
        {
            "case_date":"2021-04-16",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":50815,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":464
        },
        {
            "case_date":"2021-04-17",
            "total_vaccinations":1456793,
            "people_vaccinated":1264811,
            "people_fully_vaccinated":191982,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":51500,
            "total_vaccinated_per_hundred":1.33,
            "people_vaccinated_per_hundred":1.15,
            "people_fully_vaccinated_per_hundred":0.18,
            "daily_vaccinations_per_million":470
        },
        {
            "case_date":"2021-04-18",
            "total_vaccinations":1477757,
            "people_vaccinated":1279223,
            "people_fully_vaccinated":198534,
            "daily_vaccinations_raw":20964,
            "daily_vaccinations":48302,
            "total_vaccinated_per_hundred":1.35,
            "people_vaccinated_per_hundred":1.17,
            "people_fully_vaccinated_per_hundred":0.18,
            "daily_vaccinations_per_million":441
        },
        {
            "case_date":"2021-04-19",
            "total_vaccinations":1507547,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":29790,
            "daily_vaccinations":43607,
            "total_vaccinated_per_hundred":1.38,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":398
        },
        {
            "case_date":"2021-04-20",
            "total_vaccinations":1562563,
            "people_vaccinated":1353107,
            "people_fully_vaccinated":209456,
            "daily_vaccinations_raw":55016,
            "daily_vaccinations":43835,
            "total_vaccinated_per_hundred":1.43,
            "people_vaccinated_per_hundred":1.23,
            "people_fully_vaccinated_per_hundred":0.19,
            "daily_vaccinations_per_million":400
        },
        {
            "case_date":"2021-04-21",
            "total_vaccinations":1612420,
            "people_vaccinated":1397628,
            "people_fully_vaccinated":214792,
            "daily_vaccinations_raw":49857,
            "daily_vaccinations":42866,
            "total_vaccinated_per_hundred":1.47,
            "people_vaccinated_per_hundred":1.28,
            "people_fully_vaccinated_per_hundred":0.2,
            "daily_vaccinations_per_million":391
        },
        {
            "case_date":"2021-04-22",
            "total_vaccinations":1666687,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":54267,
            "daily_vaccinations":43741,
            "total_vaccinated_per_hundred":1.52,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":399
        },
        {
            "case_date":"2021-04-23",
            "total_vaccinations":1732359,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":65672,
            "daily_vaccinations":46245,
            "total_vaccinated_per_hundred":1.58,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":422
        },
        {
            "case_date":"2021-04-24",
            "total_vaccinations":1753465,
            "people_vaccinated":1522696,
            "people_fully_vaccinated":230769,
            "daily_vaccinations_raw":21106,
            "daily_vaccinations":42382,
            "total_vaccinated_per_hundred":1.6,
            "people_vaccinated_per_hundred":1.39,
            "people_fully_vaccinated_per_hundred":0.21,
            "daily_vaccinations_per_million":387
        },
        {
            "case_date":"2021-04-25",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":40421,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":369
        },
        {
            "case_date":"2021-04-26",
            "total_vaccinations":1767940,
            "people_vaccinated":1529948,
            "people_fully_vaccinated":237992,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":37199,
            "total_vaccinated_per_hundred":1.61,
            "people_vaccinated_per_hundred":1.4,
            "people_fully_vaccinated_per_hundred":0.22,
            "daily_vaccinations_per_million":339
        },
        {
            "case_date":"2021-04-27",
            "total_vaccinations":1809801,
            "people_vaccinated":1562815,
            "people_fully_vaccinated":246986,
            "daily_vaccinations_raw":41861,
            "daily_vaccinations":35320,
            "total_vaccinated_per_hundred":1.65,
            "people_vaccinated_per_hundred":1.43,
            "people_fully_vaccinated_per_hundred":0.23,
            "daily_vaccinations_per_million":322
        },
        {
            "case_date":"2021-04-28",
            "total_vaccinations":1849566,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":39765,
            "daily_vaccinations":33878,
            "total_vaccinated_per_hundred":1.69,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":309
        },
        {
            "case_date":"2021-04-29",
            "total_vaccinations":1880975,
            "people_vaccinated":1614420,
            "people_fully_vaccinated":266555,
            "daily_vaccinations_raw":31409,
            "daily_vaccinations":30613,
            "total_vaccinated_per_hundred":1.72,
            "people_vaccinated_per_hundred":1.47,
            "people_fully_vaccinated_per_hundred":0.24,
            "daily_vaccinations_per_million":279
        },
        {
            "case_date":"2021-04-30",
            "total_vaccinations":1919851,
            "people_vaccinated":1639806,
            "people_fully_vaccinated":280045,
            "daily_vaccinations_raw":38876,
            "daily_vaccinations":26785,
            "total_vaccinated_per_hundred":1.75,
            "people_vaccinated_per_hundred":1.5,
            "people_fully_vaccinated_per_hundred":0.26,
            "daily_vaccinations_per_million":244
        },
        {
            "case_date":"2021-05-01",
            "total_vaccinations":1941196,
            "people_vaccinated":1656643,
            "people_fully_vaccinated":284553,
            "daily_vaccinations_raw":21345,
            "daily_vaccinations":26819,
            "total_vaccinated_per_hundred":1.77,
            "people_vaccinated_per_hundred":1.51,
            "people_fully_vaccinated_per_hundred":0.26,
            "daily_vaccinations_per_million":245
        },
        {
            "case_date":"2021-05-02",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":29929,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":273
        },
        {
            "case_date":"2021-05-03",
            "total_vaccinations":1999214,
            "people_vaccinated":1689829,
            "people_fully_vaccinated":309385,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":33039,
            "total_vaccinated_per_hundred":1.82,
            "people_vaccinated_per_hundred":1.54,
            "people_fully_vaccinated_per_hundred":0.28,
            "daily_vaccinations_per_million":302
        },
        {
            "case_date":"2021-05-04",
            "total_vaccinations":2065235,
            "people_vaccinated":1744649,
            "people_fully_vaccinated":320586,
            "daily_vaccinations_raw":66021,
            "daily_vaccinations":36491,
            "total_vaccinated_per_hundred":1.88,
            "people_vaccinated_per_hundred":1.59,
            "people_fully_vaccinated_per_hundred":0.29,
            "daily_vaccinations_per_million":333
        },
        {
            "case_date":"2021-05-05",
            "total_vaccinations":2129185,
            "people_vaccinated":1786480,
            "people_fully_vaccinated":342705,
            "daily_vaccinations_raw":63950,
            "daily_vaccinations":39946,
            "total_vaccinated_per_hundred":1.94,
            "people_vaccinated_per_hundred":1.63,
            "people_fully_vaccinated_per_hundred":0.31,
            "daily_vaccinations_per_million":365
        },
        {
            "case_date":"2021-05-06",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":48687,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":444
        },
        {
            "case_date":"2021-05-07",
            "total_vaccinations":2314377,
            "people_vaccinated":1892934,
            "people_fully_vaccinated":421443,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":56361,
            "total_vaccinated_per_hundred":2.11,
            "people_vaccinated_per_hundred":1.73,
            "people_fully_vaccinated_per_hundred":0.38,
            "daily_vaccinations_per_million":514
        },
        {
            "case_date":"2021-05-08",
            "total_vaccinations":2395494,
            "people_vaccinated":1951698,
            "people_fully_vaccinated":443796,
            "daily_vaccinations_raw":81117,
            "daily_vaccinations":64900,
            "total_vaccinated_per_hundred":2.19,
            "people_vaccinated_per_hundred":1.78,
            "people_fully_vaccinated_per_hundred":0.4,
            "daily_vaccinations_per_million":592
        },
        {
            "case_date":"2021-05-09",
            "total_vaccinations":2408781,
            "people_vaccinated":1957511,
            "people_fully_vaccinated":451270,
            "daily_vaccinations_raw":13287,
            "daily_vaccinations":62654,
            "total_vaccinated_per_hundred":2.2,
            "people_vaccinated_per_hundred":1.79,
            "people_fully_vaccinated_per_hundred":0.41,
            "daily_vaccinations_per_million":572
        },
        {
            "case_date":"2021-05-10",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":68030,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":621
        },
        {
            "case_date":"2021-05-11",
            "total_vaccinations":2542066,
            "people_vaccinated":2024953,
            "people_fully_vaccinated":517113,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":68119,
            "total_vaccinated_per_hundred":2.32,
            "people_vaccinated_per_hundred":1.85,
            "people_fully_vaccinated_per_hundred":0.47,
            "daily_vaccinations_per_million":622
        },
        {
            "case_date":"2021-05-12",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":71312,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":651
        },
        {
            "case_date":"2021-05-13",
            "total_vaccinations":2714677,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":70414,
            "total_vaccinated_per_hundred":2.48,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":643
        },
        {
            "case_date":"2021-05-14",
            "total_vaccinations":2790287,
            "people_vaccinated":2154233,
            "people_fully_vaccinated":636054,
            "daily_vaccinations_raw":75610,
            "daily_vaccinations":67987,
            "total_vaccinated_per_hundred":2.55,
            "people_vaccinated_per_hundred":1.97,
            "people_fully_vaccinated_per_hundred":0.58,
            "daily_vaccinations_per_million":620
        },
        {
            "case_date":"2021-05-15",
            "total_vaccinations":2921196,
            "people_vaccinated":2245397,
            "people_fully_vaccinated":675799,
            "daily_vaccinations_raw":130909,
            "daily_vaccinations":75100,
            "total_vaccinated_per_hundred":2.67,
            "people_vaccinated_per_hundred":2.05,
            "people_fully_vaccinated_per_hundred":0.62,
            "daily_vaccinations_per_million":685
        },
        {
            "case_date":"2021-05-16",
            "total_vaccinations":3001875,
            "people_vaccinated":2282273,
            "people_fully_vaccinated":719602,
            "daily_vaccinations_raw":80679,
            "daily_vaccinations":84728,
            "total_vaccinated_per_hundred":2.74,
            "people_vaccinated_per_hundred":2.08,
            "people_fully_vaccinated_per_hundred":0.66,
            "daily_vaccinations_per_million":773
        },
        {
            "case_date":"2021-05-17",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":96464,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":880
        },
        {
            "case_date":"2021-05-18",
            "total_vaccinations":3299470,
            "people_vaccinated":2512942,
            "people_fully_vaccinated":786528,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":108201,
            "total_vaccinated_per_hundred":3.01,
            "people_vaccinated_per_hundred":2.29,
            "people_fully_vaccinated_per_hundred":0.72,
            "daily_vaccinations_per_million":987
        },
        {
            "case_date":"2021-05-19",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":125788,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1148
        },
        {
            "case_date":"2021-05-20",
            "total_vaccinations":3718308,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":143376,
            "total_vaccinated_per_hundred":3.39,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1308
        },
        {
            "case_date":"2021-05-21",
            "total_vaccinations":3956292,
            "people_vaccinated":3030579,
            "people_fully_vaccinated":925713,
            "daily_vaccinations_raw":237984,
            "daily_vaccinations":166572,
            "total_vaccinated_per_hundred":3.61,
            "people_vaccinated_per_hundred":2.77,
            "people_fully_vaccinated_per_hundred":0.84,
            "daily_vaccinations_per_million":1520
        },
        {
            "case_date":"2021-05-22",
            "total_vaccinations":4097425,
            "people_vaccinated":3147486,
            "people_fully_vaccinated":949939,
            "daily_vaccinations_raw":141133,
            "daily_vaccinations":168033,
            "total_vaccinated_per_hundred":3.74,
            "people_vaccinated_per_hundred":2.87,
            "people_fully_vaccinated_per_hundred":0.87,
            "daily_vaccinations_per_million":1533
        },
        {
            "case_date":"2021-05-23",
            "total_vaccinations":4169905,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":72480,
            "daily_vaccinations":166861,
            "total_vaccinated_per_hundred":3.81,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1523
        },
        {
            "case_date":"2021-05-24",
            "total_vaccinations":4305575,
            "people_vaccinated":3318646,
            "people_fully_vaccinated":986929,
            "daily_vaccinations_raw":135670,
            "daily_vaccinations":164986,
            "total_vaccinated_per_hundred":3.93,
            "people_vaccinated_per_hundred":3.03,
            "people_fully_vaccinated_per_hundred":0.9,
            "daily_vaccinations_per_million":1506
        },
        {
            "case_date":"2021-05-25",
            "total_vaccinations":4495375,
            "people_vaccinated":3466314,
            "people_fully_vaccinated":1029061,
            "daily_vaccinations_raw":189800,
            "daily_vaccinations":170844,
            "total_vaccinated_per_hundred":4.1,
            "people_vaccinated_per_hundred":3.16,
            "people_fully_vaccinated_per_hundred":0.94,
            "daily_vaccinations_per_million":1559
        },
        {
            "case_date":"2021-05-26",
            "total_vaccinations":4666358,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":170983,
            "daily_vaccinations":165353,
            "total_vaccinated_per_hundred":4.26,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1509
        },
        {
            "case_date":"2021-05-27",
            "total_vaccinations":4862358,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":196000,
            "daily_vaccinations":163436,
            "total_vaccinated_per_hundred":4.44,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1491
        },
        {
            "case_date":"2021-05-28",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":144598,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1320
        },
        {
            "case_date":"2021-05-29",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":139596,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1274
        },
        {
            "case_date":"2021-05-30",
            "total_vaccinations":5180721,
            "people_vaccinated":3974350,
            "people_fully_vaccinated":1206371,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":144402,
            "total_vaccinated_per_hundred":4.73,
            "people_vaccinated_per_hundred":3.63,
            "people_fully_vaccinated_per_hundred":1.1,
            "daily_vaccinations_per_million":1318
        },
        {
            "case_date":"2021-05-31",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":139410,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1272
        },
        {
            "case_date":"2021-06-01",
            "total_vaccinations":5382172,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":126685,
            "total_vaccinated_per_hundred":4.91,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1156
        },
        {
            "case_date":"2021-06-02",
            "total_vaccinations":5517523,
            "people_vaccinated":4174416,
            "people_fully_vaccinated":1343107,
            "daily_vaccinations_raw":135351,
            "daily_vaccinations":121595,
            "total_vaccinated_per_hundred":5.04,
            "people_vaccinated_per_hundred":3.81,
            "people_fully_vaccinated_per_hundred":1.23,
            "daily_vaccinations_per_million":1110
        },
        {
            "case_date":"2021-06-03",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":115824,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1057
        },
        {
            "case_date":"2021-06-04",
            "total_vaccinations":5828735,
            "people_vaccinated":4343914,
            "people_fully_vaccinated":1484821,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":122894,
            "total_vaccinated_per_hundred":5.32,
            "people_vaccinated_per_hundred":3.96,
            "people_fully_vaccinated_per_hundred":1.35,
            "daily_vaccinations_per_million":1121
        },
        {
            "case_date":"2021-06-05",
            "total_vaccinations":5907255,
            "people_vaccinated":4386467,
            "people_fully_vaccinated":1520788,
            "daily_vaccinations_raw":78520,
            "daily_vaccinations":118951,
            "total_vaccinated_per_hundred":5.39,
            "people_vaccinated_per_hundred":4,
            "people_fully_vaccinated_per_hundred":1.39,
            "daily_vaccinations_per_million":1086
        },
        {
            "case_date":"2021-06-06",
            "total_vaccinations":5965651,
            "people_vaccinated":4421319,
            "people_fully_vaccinated":1544332,
            "daily_vaccinations_raw":58396,
            "daily_vaccinations":112133,
            "total_vaccinated_per_hundred":5.44,
            "people_vaccinated_per_hundred":4.03,
            "people_fully_vaccinated_per_hundred":1.41,
            "daily_vaccinations_per_million":1023
        },
        {
            "case_date":"2021-06-07",
            "total_vaccinations":6096208,
            "people_vaccinated":4491948,
            "people_fully_vaccinated":1604260,
            "daily_vaccinations_raw":130557,
            "daily_vaccinations":116394,
            "total_vaccinated_per_hundred":5.56,
            "people_vaccinated_per_hundred":4.1,
            "people_fully_vaccinated_per_hundred":1.46,
            "daily_vaccinations_per_million":1062
        },
        {
            "case_date":"2021-06-08",
            "total_vaccinations":6314548,
            "people_vaccinated":4632826,
            "people_fully_vaccinated":1681722,
            "daily_vaccinations_raw":218340,
            "daily_vaccinations":133197,
            "total_vaccinated_per_hundred":5.76,
            "people_vaccinated_per_hundred":4.23,
            "people_fully_vaccinated_per_hundred":1.53,
            "daily_vaccinations_per_million":1216
        },
        {
            "case_date":"2021-06-09",
            "total_vaccinations":6470776,
            "people_vaccinated":4724263,
            "people_fully_vaccinated":1746513,
            "daily_vaccinations_raw":156228,
            "daily_vaccinations":136179,
            "total_vaccinated_per_hundred":5.91,
            "people_vaccinated_per_hundred":4.31,
            "people_fully_vaccinated_per_hundred":1.59,
            "daily_vaccinations_per_million":1243
        },
        {
            "case_date":"2021-06-10",
            "total_vaccinations":6614417,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":143641,
            "daily_vaccinations":134470,
            "total_vaccinated_per_hundred":6.04,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1227
        },
        {
            "case_date":"2021-06-11",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":130500,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1191
        },
        {
            "case_date":"2021-06-12",
            "total_vaccinations":6870054,
            "people_vaccinated":5014582,
            "people_fully_vaccinated":1855472,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":137543,
            "total_vaccinated_per_hundred":6.27,
            "people_vaccinated_per_hundred":4.58,
            "people_fully_vaccinated_per_hundred":1.69,
            "daily_vaccinations_per_million":1255
        },
        {
            "case_date":"2021-06-13",
            "total_vaccinations":6948549,
            "people_vaccinated":5068855,
            "people_fully_vaccinated":1879694,
            "daily_vaccinations_raw":78495,
            "daily_vaccinations":140414,
            "total_vaccinated_per_hundred":6.34,
            "people_vaccinated_per_hundred":4.63,
            "people_fully_vaccinated_per_hundred":1.72,
            "daily_vaccinations_per_million":1281
        },
        {
            "case_date":"2021-06-14",
            "total_vaccinations":7045380,
            "people_vaccinated":5132000,
            "people_fully_vaccinated":1903000,
            "daily_vaccinations_raw":96831,
            "daily_vaccinations":135596,
            "total_vaccinated_per_hundred":6.43,
            "people_vaccinated_per_hundred":4.68,
            "people_fully_vaccinated_per_hundred":1.74,
            "daily_vaccinations_per_million":1237
        },
        {
            "case_date":"2021-06-15",
            "total_vaccinations":7368309,
            "people_vaccinated":5392859,
            "people_fully_vaccinated":1975450,
            "daily_vaccinations_raw":322929,
            "daily_vaccinations":150537,
            "total_vaccinated_per_hundred":6.72,
            "people_vaccinated_per_hundred":4.92,
            "people_fully_vaccinated_per_hundred":1.8,
            "daily_vaccinations_per_million":1374
        },
        {
            "case_date":"2021-06-16",
            "total_vaccinations":7563241,
            "people_vaccinated":5551087,
            "people_fully_vaccinated":2012154,
            "daily_vaccinations_raw":194932,
            "daily_vaccinations":156066,
            "total_vaccinated_per_hundred":6.9,
            "people_vaccinated_per_hundred":5.07,
            "people_fully_vaccinated_per_hundred":1.84,
            "daily_vaccinations_per_million":1424
        },
        {
            "case_date":"2021-06-17",
            "total_vaccinations":7848392,
            "people_vaccinated":5783258,
            "people_fully_vaccinated":2065134,
            "daily_vaccinations_raw":285151,
            "daily_vaccinations":176282,
            "total_vaccinated_per_hundred":7.16,
            "people_vaccinated_per_hundred":5.28,
            "people_fully_vaccinated_per_hundred":1.88,
            "daily_vaccinations_per_million":1609
        },
        {
            "case_date":"2021-06-18",
            "total_vaccinations":8050711,
            "people_vaccinated":5953810,
            "people_fully_vaccinated":2096901,
            "daily_vaccinations_raw":202319,
            "daily_vaccinations":186925,
            "total_vaccinated_per_hundred":7.35,
            "people_vaccinated_per_hundred":5.43,
            "people_fully_vaccinated_per_hundred":1.91,
            "daily_vaccinations_per_million":1706
        },
        {
            "case_date":"2021-06-19",
            "total_vaccinations":8222759,
            "people_vaccinated":6102625,
            "people_fully_vaccinated":2120134,
            "daily_vaccinations_raw":172048,
            "daily_vaccinations":193244,
            "total_vaccinated_per_hundred":7.5,
            "people_vaccinated_per_hundred":5.57,
            "people_fully_vaccinated_per_hundred":1.93,
            "daily_vaccinations_per_million":1763
        },
        {
            "case_date":"2021-06-20",
            "total_vaccinations":8407342,
            "people_vaccinated":6253400,
            "people_fully_vaccinated":2153942,
            "daily_vaccinations_raw":184583,
            "daily_vaccinations":208399,
            "total_vaccinated_per_hundred":7.67,
            "people_vaccinated_per_hundred":5.71,
            "people_fully_vaccinated_per_hundred":1.97,
            "daily_vaccinations_per_million":1902
        },
        {
            "case_date":"2021-06-21",
            "total_vaccinations":8591406,
            "people_vaccinated":7045380,
            "people_fully_vaccinated":2183489,
            "daily_vaccinations_raw":184064,
            "daily_vaccinations":220861,
            "total_vaccinated_per_hundred":7.84,
            "people_vaccinated_per_hundred":6.43,
            "people_fully_vaccinated_per_hundred":1.99,
            "daily_vaccinations_per_million":2016
        },
        {
            "case_date":"2021-06-22",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":208700,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1905
        },
        {
            "case_date":"2021-06-23",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":214824,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1960
        },
        {
            "case_date":"2021-06-24",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":208060,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1899
        },
        {
            "case_date":"2021-06-25",
            "total_vaccinations":9542612,
            "people_vaccinated":7295715,
            "people_fully_vaccinated":2246897,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":213129,
            "total_vaccinated_per_hundred":8.71,
            "people_vaccinated_per_hundred":6.66,
            "people_fully_vaccinated_per_hundred":2.05,
            "daily_vaccinations_per_million":1945
        },
        {
            "case_date":"2021-06-26",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":225893,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2061
        },
        {
            "case_date":"2021-06-27",
            "total_vaccinations":10065414,
            "people_vaccinated":7538128,
            "people_fully_vaccinated":2527286,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":236867,
            "total_vaccinated_per_hundred":9.19,
            "people_vaccinated_per_hundred":6.88,
            "people_fully_vaccinated_per_hundred":2.31,
            "daily_vaccinations_per_million":2162
        },
        {
            "case_date":"2021-06-28",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":222783,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2033
        },
        {
            "case_date":"2021-06-29",
            "total_vaccinations":10236354,
            "people_vaccinated":7665974,
            "people_fully_vaccinated":2570380,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":201021,
            "total_vaccinated_per_hundred":9.34,
            "people_vaccinated_per_hundred":7,
            "people_fully_vaccinated_per_hundred":2.35,
            "daily_vaccinations_per_million":1834
        },
        {
            "case_date":"2021-06-30",
            "total_vaccinations":10443407,
            "people_vaccinated":7810469,
            "people_fully_vaccinated":2632938,
            "daily_vaccinations_raw":207053,
            "daily_vaccinations":196628,
            "total_vaccinated_per_hundred":9.53,
            "people_vaccinated_per_hundred":7.13,
            "people_fully_vaccinated_per_hundred":2.4,
            "daily_vaccinations_per_million":1794
        },
        {
            "case_date":"2021-07-01",
            "total_vaccinations":10703704,
            "people_vaccinated":8002640,
            "people_fully_vaccinated":2701064,
            "daily_vaccinations_raw":260297,
            "daily_vaccinations":199842,
            "total_vaccinated_per_hundred":9.77,
            "people_vaccinated_per_hundred":7.3,
            "people_fully_vaccinated_per_hundred":2.46,
            "daily_vaccinations_per_million":1824
        },
        {
            "case_date":"2021-07-02",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":213695,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":1950
        },
        {
            "case_date":"2021-07-03",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":224177,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2046
        },
        {
            "case_date":"2021-07-04",
            "total_vaccinations":11708029,
            "people_vaccinated":8839124,
            "people_fully_vaccinated":2868905,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":234659,
            "total_vaccinated_per_hundred":10.68,
            "people_vaccinated_per_hundred":8.07,
            "people_fully_vaccinated_per_hundred":2.62,
            "daily_vaccinations_per_million":2141
        },
        {
            "case_date":"2021-07-05",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":241005,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2199
        },
        {
            "case_date":"2021-07-06",
            "total_vaccinations":11967805,
            "people_vaccinated":9047357,
            "people_fully_vaccinated":2920448,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":247350,
            "total_vaccinated_per_hundred":10.92,
            "people_vaccinated_per_hundred":8.26,
            "people_fully_vaccinated_per_hundred":2.67,
            "daily_vaccinations_per_million":2257
        },
        {
            "case_date":"2021-07-07",
            "total_vaccinations":12179437,
            "people_vaccinated":9208070,
            "people_fully_vaccinated":2971367,
            "daily_vaccinations_raw":211632,
            "daily_vaccinations":248004,
            "total_vaccinated_per_hundred":11.11,
            "people_vaccinated_per_hundred":8.4,
            "people_fully_vaccinated_per_hundred":2.71,
            "daily_vaccinations_per_million":2263
        },
        {
            "case_date":"2021-07-08",
            "total_vaccinations":12489777,
            "people_vaccinated":9399801,
            "people_fully_vaccinated":3089976,
            "daily_vaccinations_raw":310340,
            "daily_vaccinations":255153,
            "total_vaccinated_per_hundred":11.4,
            "people_vaccinated_per_hundred":8.58,
            "people_fully_vaccinated_per_hundred":2.82,
            "daily_vaccinations_per_million":2328
        },
        {
            "case_date":"2021-07-09",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":239656,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2187
        },
        {
            "case_date":"2021-07-10",
            "total_vaccinations":12942364,
            "people_vaccinated":9576619,
            "people_fully_vaccinated":3365745,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":224159,
            "total_vaccinated_per_hundred":11.81,
            "people_vaccinated_per_hundred":8.74,
            "people_fully_vaccinated_per_hundred":3.07,
            "daily_vaccinations_per_million":2046
        },
        {
            "case_date":"2021-07-11",
            "total_vaccinations":13122277,
            "people_vaccinated":9657361,
            "people_fully_vaccinated":3464916,
            "daily_vaccinations_raw":179913,
            "daily_vaccinations":202035,
            "total_vaccinated_per_hundred":11.97,
            "people_vaccinated_per_hundred":8.81,
            "people_fully_vaccinated_per_hundred":3.16,
            "daily_vaccinations_per_million":1844
        },
        {
            "case_date":"2021-07-12",
            "total_vaccinations":13196282,
            "people_vaccinated":9669940,
            "people_fully_vaccinated":3526342,
            "daily_vaccinations_raw":74005,
            "daily_vaccinations":194052,
            "total_vaccinated_per_hundred":12.04,
            "people_vaccinated_per_hundred":8.82,
            "people_fully_vaccinated_per_hundred":3.22,
            "daily_vaccinations_per_million":1771
        },
        {
            "case_date":"2021-07-13",
            "total_vaccinations":13442299,
            "people_vaccinated":9771359,
            "people_fully_vaccinated":3670940,
            "daily_vaccinations_raw":246017,
            "daily_vaccinations":210642,
            "total_vaccinated_per_hundred":12.27,
            "people_vaccinated_per_hundred":8.92,
            "people_fully_vaccinated_per_hundred":3.35,
            "daily_vaccinations_per_million":1922
        },
        {
            "case_date":"2021-07-14",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":225567,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2058
        },
        {
            "case_date":"2021-07-15",
            "total_vaccinations":14074514,
            "people_vaccinated":10026722,
            "people_fully_vaccinated":4047792,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":226391,
            "total_vaccinated_per_hundred":12.84,
            "people_vaccinated_per_hundred":9.15,
            "people_fully_vaccinated_per_hundred":3.69,
            "daily_vaccinations_per_million":2066
        },
        {
            "case_date":"2021-07-16",
            "total_vaccinations":14465786,
            "people_vaccinated":10177126,
            "people_fully_vaccinated":4288660,
            "daily_vaccinations_raw":391272,
            "daily_vaccinations":249959,
            "total_vaccinated_per_hundred":13.2,
            "people_vaccinated_per_hundred":9.29,
            "people_fully_vaccinated_per_hundred":3.91,
            "daily_vaccinations_per_million":2281
        },
        {
            "case_date":"2021-07-17",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":247654,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2260
        },
        {
            "case_date":"2021-07-18",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":251975,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2299
        },
        {
            "case_date":"2021-07-19",
            "total_vaccinations":15096261,
            "people_vaccinated":10388188,
            "people_fully_vaccinated":4708073,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":271426,
            "total_vaccinated_per_hundred":13.78,
            "people_vaccinated_per_hundred":9.48,
            "people_fully_vaccinated_per_hundred":4.3,
            "daily_vaccinations_per_million":2477
        },
        {
            "case_date":"2021-07-20",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":273445,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2495
        },
        {
            "case_date":"2021-07-21",
            "total_vaccinations":15616562,
            "people_vaccinated":10585261,
            "people_fully_vaccinated":5031301,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":265451,
            "total_vaccinated_per_hundred":14.25,
            "people_vaccinated_per_hundred":9.66,
            "people_fully_vaccinated_per_hundred":4.59,
            "daily_vaccinations_per_million":2422
        },
        {
            "case_date":"2021-07-22",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":278129,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2538
        },
        {
            "case_date":"2021-07-23",
            "total_vaccinations":16426267,
            "people_vaccinated":10866238,
            "people_fully_vaccinated":5560029,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":280069,
            "total_vaccinated_per_hundred":14.99,
            "people_vaccinated_per_hundred":9.92,
            "people_fully_vaccinated_per_hundred":5.07,
            "daily_vaccinations_per_million":2556
        },
        {
            "case_date":"2021-07-24",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":295751,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":2699
        },
        {
            "case_date":"2021-07-25",
            "total_vaccinations":17066135,
            "people_vaccinated":11082020,
            "people_fully_vaccinated":5984115,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":311433,
            "total_vaccinated_per_hundred":15.57,
            "people_vaccinated_per_hundred":10.11,
            "people_fully_vaccinated_per_hundred":5.46,
            "daily_vaccinations_per_million":2842
        },
        {
            "case_date":"2021-07-26",
            "total_vaccinations":17202421,
            "people_vaccinated":11113107,
            "people_fully_vaccinated":6089314,
            "daily_vaccinations_raw":136286,
            "daily_vaccinations":300880,
            "total_vaccinated_per_hundred":15.7,
            "people_vaccinated_per_hundred":10.14,
            "people_fully_vaccinated_per_hundred":5.56,
            "daily_vaccinations_per_million":2746
        },
        {
            "case_date":"2021-07-27",
            "total_vaccinations":17515376,
            "people_vaccinated":11204316,
            "people_fully_vaccinated":6311060,
            "daily_vaccinations_raw":312955,
            "daily_vaccinations":308424,
            "total_vaccinated_per_hundred":15.98,
            "people_vaccinated_per_hundred":10.22,
            "people_fully_vaccinated_per_hundred":5.76,
            "daily_vaccinations_per_million":2815
        },
        {
            "case_date":"2021-07-28",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":403013,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":3678
        },
        {
            "case_date":"2021-07-29",
            "total_vaccinations":19359927,
            "people_vaccinated":11524212,
            "people_fully_vaccinated":7835715,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":476930,
            "total_vaccinated_per_hundred":17.67,
            "people_vaccinated_per_hundred":10.52,
            "people_fully_vaccinated_per_hundred":7.15,
            "daily_vaccinations_per_million":4352
        },
        {
            "case_date":"2021-07-30",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":472795,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":4315
        },
        {
            "case_date":"2021-07-31",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":480791,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":4388
        },
        {
            "case_date":"2021-08-01",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":488786,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":4460
        },
        {
            "case_date":"2021-08-02",
            "total_vaccinations":20863544,
            "people_vaccinated":11747581,
            "people_fully_vaccinated":9115963,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":523018,
            "total_vaccinated_per_hundred":19.04,
            "people_vaccinated_per_hundred":10.72,
            "people_fully_vaccinated_per_hundred":8.32,
            "daily_vaccinations_per_million":4773
        },
        {
            "case_date":"2021-08-03",
            "total_vaccinations":22488705,
            "people_vaccinated":12206553,
            "people_fully_vaccinated":10282152,
            "daily_vaccinations_raw":1625161,
            "daily_vaccinations":710476,
            "total_vaccinated_per_hundred":20.52,
            "people_vaccinated_per_hundred":11.14,
            "people_fully_vaccinated_per_hundred":9.38,
            "daily_vaccinations_per_million":6484
        },
        {
            "case_date":"2021-08-04",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":629471,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":5744
        },
        {
            "case_date":"2021-08-05",
            "total_vaccinations":23199187,
            "people_vaccinated":12493997,
            "people_fully_vaccinated":10705190,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":548466,
            "total_vaccinated_per_hundred":21.17,
            "people_vaccinated_per_hundred":11.4,
            "people_fully_vaccinated_per_hundred":9.77,
            "daily_vaccinations_per_million":5005
        },
        {
            "case_date":"2021-08-06",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":580044,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":5293
        },
        {
            "case_date":"2021-08-07",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":611622,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":5581
        },
        {
            "case_date":"2021-08-08",
            "total_vaccinations":24990042,
            "people_vaccinated":13375452,
            "people_fully_vaccinated":11614590,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":643200,
            "total_vaccinated_per_hundred":22.81,
            "people_vaccinated_per_hundred":12.21,
            "people_fully_vaccinated_per_hundred":10.6,
            "daily_vaccinations_per_million":5870
        },
        {
            "case_date":"2021-08-09",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":643664,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":5874
        },
        {
            "case_date":"2021-08-10",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":465663,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":4249
        },
        {
            "case_date":"2021-08-11",
            "total_vaccinations":26127502,
            "people_vaccinated":14100119,
            "people_fully_vaccinated":12027383,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":469079,
            "total_vaccinated_per_hundred":23.84,
            "people_vaccinated_per_hundred":12.87,
            "people_fully_vaccinated_per_hundred":10.98,
            "daily_vaccinations_per_million":4281
        },
        {
            "case_date":"2021-08-12",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":478309,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":4365
        },
        {
            "case_date":"2021-08-13",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":453008,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":4134
        },
        {
            "case_date":"2021-08-14",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":427707,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":3903
        },
        {
            "case_date":"2021-08-15",
            "total_vaccinations":27806881,
            "people_vaccinated":15241864,
            "people_fully_vaccinated":12565017,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":402406,
            "total_vaccinated_per_hundred":25.38,
            "people_vaccinated_per_hundred":13.91,
            "people_fully_vaccinated_per_hundred":11.47,
            "daily_vaccinations_per_million":3672
        },
        {
            "case_date":"2021-08-16",
            "total_vaccinations":28308493,
            "people_vaccinated":15565411,
            "people_fully_vaccinated":12743082,
            "daily_vaccinations_raw":501612,
            "daily_vaccinations":419900,
            "total_vaccinated_per_hundred":25.83,
            "people_vaccinated_per_hundred":14.2,
            "people_fully_vaccinated_per_hundred":11.63,
            "daily_vaccinations_per_million":3832
        },
        {
            "case_date":"2021-08-17",
            "total_vaccinations":0,
            "people_vaccinated":0,
            "people_fully_vaccinated":0,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":424217,
            "total_vaccinated_per_hundred":0,
            "people_vaccinated_per_hundred":0,
            "people_fully_vaccinated_per_hundred":0,
            "daily_vaccinations_per_million":3871
        },
        {
            "case_date":"2021-08-18",
            "total_vaccinations":29127240,
            "people_vaccinated":16250043,
            "people_fully_vaccinated":12877197,
            "daily_vaccinations_raw":0,
            "daily_vaccinations":428534,
            "total_vaccinated_per_hundred":26.58,
            "people_vaccinated_per_hundred":14.83,
            "people_fully_vaccinated_per_hundred":11.75,
            "daily_vaccinations_per_million":3911
        }
    ]
};

module.exports = vaccinationData;
